name: Toggle EKS Environment (POC)

on:
  workflow_dispatch:
    inputs:
      action:
        description: up or down
        required: true
        default: up
        type: choice
        options: [up, down]

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate toggle (dry run)
        run: |
          echo "=== POC DRY RUN ==="
          echo "Action chosen: ${{ github.event.inputs.action }}"
          if [[ "${{ github.event.inputs.action }}" == "down" ]]; then
            echo "[DRY-RUN] Would scale workloads to 0"
            echo "[DRY-RUN] Would delete ingress"
            echo "[DRY-RUN] Would scale nodegroups to 0"
            echo "Environment would be DOWN"
          else
            echo "[DRY-RUN] Would scale nodegroups up"
            echo "[DRY-RUN] Would wait for nodes"
            echo "[DRY-RUN] Would scale workloads up"
            echo "Environment would be UP"
          fi
